name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
        
    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
       # Bazel version to install e.g. 1.2.1, 2.0.0, ...
       version: 3.1.0 # optional, default is 2.0.0
        
    - name: Clone TensorFlow
      uses: actions/checkout@v2
      with:
        repository: tensorflow/tensorflow
        path: tensorflow
       
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
  
    - name: workspace bazel
      run: touch WORKSPACE

    - name: run Bazel command
      uses: ngalaiko/bazel-action/2.0.0@master
      with:
        working_dir: tensorflow
        args: build -c opt //tensorflow/lite/c:tensorflowlite_c

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
